spring.application.name=neuropp-ivina-api

server.port=8080

# Banco PostgreSQL do projeto NeuroPP
# Usamos a porta 5433 porque a 5432 já está ocupada por outro projeto.
spring.datasource.url=jdbc:postgresql://localhost:5433/neuropp_db
spring.datasource.username=neuropp_user
spring.datasource.password=neuropp_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Durante o desenvolvimento, o Hibernate pode criar/atualizar as tabelas automaticamente.
spring.jpa.hibernate.ddl-auto=update

# Mostra os comandos SQL no terminal para estudarmos o que está acontecendo.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false